#ifndef _DFU_BOOTLOADER_USERCONFIG_H_
#define _DFU_BOOTLOADER_USERCONFIG_H_

#define DFU_CIPHER _DISABLE
#define DFU_BOOTSTRAP_GPIO _DISABLE
#define DFU_BOOTSTRAP_PULL _DISABLE

#define DFU_STR_MANUF       "Happen Interactive"
#define DFU_STR_PRODUCT     "SS-1 DFU BOOT MODE"

#endif //_DFU_BOOTLOADER_USERCONFIG_H_